### ISSUE TITLE
Tagのページで２点不明点あり

### ISSUE THREAD

**Issue by kawakoshi** [kawakoshi/cavalry_kwks#1]
- タグをアクティブにするという欄で出ている機能がどういうものかわからない。
[疑問] 要素をタグにドラッグして割り当てる際に alt/option を押したままにしておくと、マウスを上にしたときにもそのタグが有効になります。(原文：Holding alt/option as you drag Elements on to tags to assign them will also activate that tag on mouse up.）

- 英語として訳せない
タグのネスト化のところの参考例の最後の一文
Be as granular as you like!

**Comment by ginrei** [comment]
- エレメンツをドラッグしてタグに登録するときにも、alt/optionを押していればドロップ後マウスボタンを離した時にそのタグが付いている要素をアクティブにできます。

- 好きなだけ(階層やタグの分類を)細かくしてね！

**Comment by kawakoshi** [comment]
- 試してみてわかりました！
(Aのタグを選択中に)エレメンツをBのタグにドラッグして登録する場合、alt/option押していると、選択がBのタグになるよってことみたいです。なので、Aのタグを選択してAのタグにドラッグする際alt/optionを押していて何も変わらなかった！　みたいなのを繰り返してました。

- 機械翻訳は「好きなだけ粒状にしてください」と言われてよくわかりませんでしたがそういう意味だったですね！ありがとうございます！
